variables:
  ${{ if eq(variables['Build.SourceBranchName'], 'develop') }}:
    Ambiente: dev
  ${{ if eq(variables['Build.SourceBranchName'], 'hml') }}:
    Ambiente: hml
  ${{ if eq(variables['Build.SourceBranchName'], 'master') }}:
    Ambiente: prod

  ArtifactName: 'GvReportBuildApi-${{ variables.Ambiente }}'
